name: onuncu_dal
description: "Turk mitolojisinden ilham alan 2D AFK Idle RPG"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any
  flame: ^1.18.0
  flame_audio: ^2.10.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_riverpod: ^2.5.0
  go_router: ^14.0.0
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/heroes/barbarian/
    - assets/images/heroes/black_knight/
    - assets/images/heroes/ninja/
    - assets/images/heroes/archer/
    - assets/images/heroes/red_mage/
    - assets/images/enemies/boss/wight_knight/
    - assets/images/enemies/world1/goblin/
    - assets/images/enemies/world1/mushroom/
    - assets/images/enemies/world1/skeleton/
    - assets/images/enemies/world1/flying_eye/
    - assets/images/enemies/world1/bat/
    - assets/images/backgrounds/world1/
    - assets/images/backgrounds/world2/
    - assets/images/backgrounds/world4/
    - assets/images/ui/hud/
    - assets/images/ui/frames/
    - assets/images/ui/icons/
